/*
 * The Genesis Project
 * Copyright (C) 2005-2006  Summa Technologies do Brasil Ltda.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package net.java.dev.genesis.ui.swing;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.Map;

import javax.swing.ButtonGroup;
import javax.swing.FocusManager;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.RootPaneContainer;

import net.java.dev.genesis.ui.binding.AbstractBinder;
import net.java.dev.genesis.ui.binding.BoundAction;
import net.java.dev.genesis.ui.binding.BoundDataProvider;
import net.java.dev.genesis.ui.binding.BoundField;
import net.java.dev.genesis.ui.binding.BoundMember;
import net.java.dev.genesis.ui.binding.ExceptionHandler;
import net.java.dev.genesis.ui.controller.FormControllerListener;
import net.java.dev.genesis.ui.metadata.ActionMetadata;
import net.java.dev.genesis.ui.metadata.DataProviderMetadata;
import net.java.dev.genesis.ui.metadata.FieldMetadata;
import net.java.dev.genesis.ui.metadata.FormMetadata;
import net.java.dev.genesis.ui.swing.lookup.BreadthFirstComponentLookupStrategy;
import net.java.dev.genesis.ui.swing.lookup.ComponentLookupStrategy;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * <code>SwingBinder</code> is the default implementation of
 * <code>AbstractBinder</code> for Swing. This class is
 * used to link a Swing <code>Component</code> to a <code>form</code>.
 * Events generated by the <code>Component</code> are handled by
 * <code>SwingBinder</code> and passed to the <code>form</code>.
 * If the <code>form</code> state changes, <code>SwingBinder</code> will
 * reflect that in <code>Component</code>.
 */
public class SwingBinder extends AbstractBinder {
   private static final Log log = LogFactory.getLog(SwingBinder.class);

   /**
    * The key used to store the binder in a component client property.
    */
   public static final String BINDER_KEY = "genesis:SwingBinder";

   /**
    * The key used to store the property name used in a blank label
    */
   public static final String BLANK_LABEL_PROPERTY = "genesis:blankLabel";

   /**
    * The key used to store whether or not the component has blank label
    */
   public static final String BLANK_PROPERTY = "genesis:blank";

   /**
    * The key used to store the value of the button in a button group
    */
   public static final String BUTTON_GROUP_SELECTION_VALUE = 
         "genesis:buttonGroupSelectionValue";

   /**
    * The key used to store the column names of a JTable
    */
   public static final String COLUMN_NAMES = "genesis:columnNames";

   /**
    * The key used to store values for the enabled group
    */
   public static final String ENABLED_GROUP_PROPERTY = "genesis:enabledGroup";

   /**
    * The key used to store whether or not the component is bound
    */   
   public static final String GENESIS_BOUND = "genesis:boundField";

   /**
    * The key used to store the property used as a key in a JComboBox or JList
    */
   public static final String KEY_PROPERTY = "genesis:key";

   /**
    * The key used to store the value property in a JComboBox or JList
    */   
   public static final String VALUE_PROPERTY = "genesis:value";

   /**
    * The key used to store whether or not the component is associated with
    * a virtual property
    */
   public static final String VIRTUAL = "genesis:virtual";

   /**
    * The key used to store values for the visible group
    */
   public static final String VISIBLE_GROUP_PROPERTY = "genesis:visibleGroup";

   /**
    * The key used to store values for the widget group
    */   
   public static final String WIDGET_GROUP_PROPERTY = "genesis:widgetGroup";

   private final ComponentBinderRegistryFactory factory =
      ComponentBinderRegistryFactory.getInstance();
   private final Component root;
   private final ComponentLookupStrategy lookupStrategy;
   private final Map buttonGroupsMap = new HashMap();
   private final Map componentBinders = new HashMap();
   private final Map groupBinders = new IdentityHashMap();
   private final ActionListener defaultButtonListener;

   /**
    * Constructs a new <code>SwingBinder</code> initialized with the
    * <code>component</code> and the <code>form</code>. The <code>component</code>
    * will act as a <code>ViewHandler</code> and all <code>BeforeAction</code>
    * and <code>AfterAction</code> methods will be delegated to the <code>component</code>.
    * 
    * @param component the component used in binding action
    * @param form the form to be used
    * @see AbstractBinder
    */
   public SwingBinder(Component component, Object form) {
      this(component, (ComponentLookupStrategy) null, form, component, true);
   }

   /**
    * Constructs a new <code>SwingBinder</code> initialized with the
    * <code>component</code>, the specified <code>lookupStrategy</code>
    * and the <code>form</code>. 
    *
    * @param component the component used in binding action
    * @param lookupStrategy the lookup strategy to use
    * @param form the form to be used
    * 
    * @see AbstractBinder
    */
   public SwingBinder(Component component,
      ComponentLookupStrategy lookupStrategy, Object form) {
      this(component, lookupStrategy, form, component, true);
   }

   /**
    * Constructs a new <code>SwingBinder</code> initialized with the
    * <code>component</code>, the <code>form</code> and the specified
    * <code>handler</code>. 
    *
    * @param component the component used in binding action
    * @param form the form to be used
    * @param handler the view handler to use
    * 
    * @see AbstractBinder
    */
   public SwingBinder(Component component, Object form, Object handler) {
      this(component, (ComponentLookupStrategy) null, form, handler, true);
   }

   /**
    * Constructs a new <code>SwingBinder</code> initialized with the
    * <code>component</code>, the <code>lookupStrategy</code>,
    * the <code>form</code> and the specified <code>handler</code>. 
    *
    * @param component the component used in binding action
    * @param lookupStrategy the lookup strategy to use
    * @param form the form to be used
    * @param handler the view handler to use
    * 
    * @see AbstractBinder
    */
   public SwingBinder(Component component,
         ComponentLookupStrategy lookupStrategy, Object form, Object handler) {
      this(component, lookupStrategy, form, handler, true);
   }

   /**
    * Constructs a new <code>SwingBinder</code> initialized with the
    * <code>component</code>, the <code>lookupStrategy</code>,
    * the <code>form</code> and the specified <code>handler</code>. 
    *
    * @param component the component used in binding action
    * @param lookupStrategy the lookup strategy to use
    * @param form the form to be used
    * @param handler the view handler to use
    * @param bindDefaultButton whether the binder should bind the default button
    * 
    * @see AbstractBinder
    */
   public SwingBinder(Component component,
      ComponentLookupStrategy lookupStrategy, Object form, Object handler, boolean bindDefaultButton) {
      super(form, handler);
      this.root = component;
      this.lookupStrategy = (lookupStrategy == null)
         ? createComponentLookupStrategy() : lookupStrategy;
      this.defaultButtonListener = bindDefaultButton ? createDefautButtonListener()
            : null;
   }

   /**
    * Retrieves the lookup strategy in use by the binder
    *
    * @return the lookup strategy in use by the binder
    */
   public ComponentLookupStrategy getLookupStrategy() {
      return lookupStrategy;
   }

   /**
    * Retrieves the root Component of the binder
    *
    * @return the root Component of the binder
    */
   public Component getRoot() {
      return root;
   }

   /**
    * Creates and returns a new instance of SwingExceptionHandler.
    * Override to change the default ExceptionHandler to use.
    *
    * @return a new instance of an ExceptionHandler
    */
   protected ExceptionHandler createExceptionHandler() {
      return new SwingExceptionHandler(getRoot());
   }

   /**
    * Associates the specified component with the specified name.
    * 
    * @param name the name with which the specified component is to be associated.
    * @param component the component to be associated with the specified name.
    * @return previous component associated with specified name, or <tt>null</tt>
    *          if none.
    */
   public Component register(String name, Component component) {
      return getLookupStrategy().register(name, component);
   }

   /**
    * Associates the specified component binder with the field with the specified name.
    * Use this to register a custom component binder to a specified field.
    * 
    * @param componentName the name with which the specified component binder is to be associated.
    * @param binder the component binder to be associated with the specified name.
    * @return previous component associated with specified name, or <tt>null</tt>
    *          if none.
    */
   public ComponentBinder registerComponentBinder(String componentName,
      ComponentBinder binder) {
      return (ComponentBinder) componentBinders.put(componentName, binder);
   }

   /**
    * Associates the specified ButtonGroup with the field with the specified name.
    * Use this to bind ButtonGroups.
    * 
    * @param name the name with which the specified ButtonGroup is to be associated.
    * @param buttonGroup the ButtonGroup to be associated with the specified name.
    * @return the buttonGroup.
    */
   public ButtonGroup registerButtonGroup(String name, ButtonGroup buttonGroup) {
      buttonGroupsMap.put(name, buttonGroup);

      return buttonGroup;
   }

   /**
    * Associates the specified ButtonGroup with the field with the specified name and
    * with the GroupBinder to use in this association. Use this to bind ButtonGroups.
    * 
    * @param name the name with which the specified ButtonGroup is to be associated.
    * @param buttonGroup the ButtonGroup to be associated with the specified name.
    * @param groupBinder the specified GroupBinder to use
    * @return the buttonGroup.
    */
   public ButtonGroup registerButtonGroup(String name, ButtonGroup buttonGroup, GroupBinder groupBinder) {
      registerButtonGroup(name, buttonGroup);
      groupBinders.put(buttonGroup, groupBinder);

      return buttonGroup;
   }

   public boolean isVirtual(Object widget) {
      return widget instanceof JComponent && isVirtual((JComponent) widget);
   }

   public boolean isVirtual(Component component) {
      return component instanceof JComponent
            && isVirtual((JComponent) component);
   }

   public boolean isVirtual(JComponent component) {
      return Boolean.TRUE.equals(component.getClientProperty(VIRTUAL));
   }

   /**
    * Creates and returns a new instance of BreadthFirstComponentLookupStrategy.
    * Override to change the default ComponentLookupStrategy to use.
    *
    * @return a new instance of a ComponentLookupStrategy
    */
   protected ComponentLookupStrategy createComponentLookupStrategy() {
      return new BreadthFirstComponentLookupStrategy();
   }

   /**
    * Returns the component name
    *
    * @return the component name
    */
   public String getName(Object component) {
      return getLookupStrategy().getName((Component) component);
   }

   protected ComponentBinder getComponentBinder(Component component) {
      ComponentBinder binder =
         (ComponentBinder) componentBinders.get(getLookupStrategy().getName(component));

      if (binder != null) {
         return binder;
      }

      return factory.get(component.getClass(), true);
   }

   protected GroupBinder getGroupBinder(ButtonGroup group) {
      GroupBinder binder = (GroupBinder) groupBinders.get(group);

      if (binder != null) {
         return binder;
      }

      return factory.getButtonGroupBinder();
   }

   /**
    * Method that does the bind. It will look in the form and associate
    * fields, actions and dataproviders with components in the UI.
    * This method should be the last one used by a binder. 
    */
   public void bind() {
      super.bind();

      bindDefaultButton();
      markBound();
   }

   protected void bindDefaultButton() {
      if (defaultButtonListener == null || !(root instanceof RootPaneContainer)) {
         return;
      }

      final JButton defaultButton = ((RootPaneContainer) root).getRootPane()
            .getDefaultButton();

      if (defaultButton == null) {
         return;
      }

      defaultButton.addActionListener(defaultButtonListener);
   }
   
   protected ActionListener createDefautButtonListener() {
      return new ActionListener() {
         public void actionPerformed(ActionEvent event) {
            Component defaultButton = (Component)event.getSource();
            Component c = FocusManager.getCurrentManager().getFocusOwner();

            if (c != null) {
               c.dispatchEvent(new FocusEvent(defaultButton, 
                     FocusEvent.FOCUS_LOST));
            }

            defaultButton.dispatchEvent(new FocusEvent(defaultButton, 
                  FocusEvent.FOCUS_GAINED));
         }
      };
   }

   protected void markBound() {
      if (root instanceof JComponent) {
         ((JComponent) root).putClientProperty(GENESIS_BOUND, Boolean.TRUE);
      }
   }

   protected BoundField bindFieldMetadata(String name,
      FormMetadata formMetadata, FieldMetadata fieldMetadata) {
      final Component component = lookupStrategy.lookup(root, name);

      if (component == null) {
         final ButtonGroup group = (ButtonGroup) buttonGroupsMap.get(name);

         if (group == null) {
            log.warn(name + " could not be found while binding " +
               getForm().getClass());

            return null;
         }

         GroupBinder binder = getGroupBinder(group);

         if (binder == null) {
            log.warn("No GroupBinder registered for " + group.getClass());

            return null;
         }

         return binder.bind(this, group, fieldMetadata);
      }

      ComponentBinder binder = getComponentBinder(component);

      if (binder == null) {
         log.warn("No ComponentBinder registered for " + component.getClass());

         return null;
      }

      return binder.bind(this, component, fieldMetadata);
   }

   protected BoundAction bindActionMetadata(String name,
      FormMetadata formMetadata, ActionMetadata actionMetadata) {
      final Component component = lookupStrategy.lookup(root, name);

      if (component == null) {
         log.warn(name + " could not be found while binding " +
            getForm().getClass());

         return null;
      }

      ComponentBinder binder = getComponentBinder(component);

      if (binder == null) {
         log.warn("No ComponentBinder registered for " + component.getClass());

         return null;
      }

      return binder.bind(this, component, actionMetadata);
   }

   protected BoundDataProvider bindDataProvider(String name,
      FormMetadata formMetadata, DataProviderMetadata dataProviderMetadata) {
      final Component component = lookupStrategy.lookup(root, name);

      if (component == null) {
         log.warn(name + " could not be found while binding " +
            getForm().getClass());

         return null;
      }

      ComponentBinder binder = getComponentBinder(component);

      if (binder == null) {
         log.warn("No ComponentBinder registered for " + component.getClass());

         return null;
      }

      return binder.bind(this, component, dataProviderMetadata);
   }

   public BoundMember getBoundMember(String name) {
      BoundMember member = super.getBoundMember(name);

      if (member == null) {
         member = (BoundMember) buttonGroupsMap.get(name);
      }

      return member;
   }

   protected FormControllerListener getFormControllerListener() {
      return (FormControllerListener) Proxy.newProxyInstance(
            Thread.currentThread().getContextClassLoader(),
            new Class[] {FormControllerListener.class}, new InvocationHandler() {
               public Object invoke(Object proxy, final Method method, 
                     final Object[] args) throws Throwable {
                  if (method.getDeclaringClass() != FormControllerListener.class || 
                        EventQueue.isDispatchThread()) {
                     return method.invoke(SwingBinder.this, args);
                  }

                  final Object[] result = new Object[1];
                  final Exception[] exception = new Exception[1];

                  EventQueue.invokeAndWait(new Runnable() {
                     public void run() {
                        try {
                           result[0] = method.invoke(SwingBinder.this, args);
                        } catch (IllegalArgumentException ex) {
                           exception[0] = ex;
                        } catch (InvocationTargetException ex) {
                           exception[0] = ex;
                        } catch (IllegalAccessException ex) {
                           exception[0] = ex;
                        }
                     }
                  });

                  if (exception[0] != null) {
                     throw exception[0];
                  }

                  return result[0];
               }
            });
   }
}
