/*
 * GeneralCustomizer.java
 *
 * Created on 24 de Agosto de 2007, 23:06
 */

package net.java.dev.genesis.plugins.netbeans.projecttype.ui.customizer;

import net.java.dev.genesis.annotation.ViewHandler;
import net.java.dev.genesis.plugins.netbeans.projecttype.GenesisProject;
import net.java.dev.genesis.ui.swing.SwingBinder;
import org.openide.util.HelpCtx;
import org.openide.util.NbBundle;

/**
 *
 * @author  Michel Graciano
 */
@ViewHandler
public class CustomizerGeneral extends GenesisCustomizerProvider.GenesisView implements HelpCtx.Provider {
    
    /** Creates a new instance of GeneralCustomizer */
    public CustomizerGeneral( GenesisProject project ) throws Exception {
        this.initComponents();
        
        this.form = new CustomizerGeneralForm( project );
        this.binder = new SwingBinder( this, form );
        this.binder.bind();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        txtProjectFolder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setLabelFor(txtProjectFolder);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, NbBundle.getMessage(CustomizerGeneral.class, "LBL_Project_Folder"));

        txtProjectFolder.setEditable(false);
        txtProjectFolder.setText("jTextField1");
        txtProjectFolder.setName("projectFolder");

        jLabel2.setText(NbBundle.getMessage(CustomizerGeneral.class, "LBL_Display_Name"));

        jTextField1.setText("jTextField1");
        jTextField1.setName("prettyName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(txtProjectFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProjectFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtProjectFolder;
    // Fim da declaração de variáveis//GEN-END:variables
    
    private SwingBinder binder;
    
    private CustomizerGeneralForm form;
    
    public HelpCtx getHelpCtx() {
        return new HelpCtx( CustomizerGeneral.class );
    }
    
    public GenesisProjectProperties getForm() {
        return this.form;
    }
    
}
